### ISSUE TITLE
This plugin block non-handled inputs types

### ISSUE THREAD

**Issue by Mrcubix** [shmkle/TemporalResampler#3]
This plugin does not emit to other elements in the pipeline when a type not handled by your plugin is detected in `ConsumeState()`

you should be wrapping everything after line 106 inside this condition :

```cs
if (State is ITabletReport report && TabletReference != null) 
{
    [...]
}
else
    OnEmit();
```

https://github.com/shmkle/TemporalResampler/blob/cbdcbd628b4be2d7600a7d72251bbdd63c5509e5/TemporalResampler/TemporalResampler.cs#L107-L183

**Comment by shmkle** [comment]
fire, will fix soon

**Comment by Mrcubix** [comment]
Turns out that plugin also prevent OTD's Binding Handler (Tip, Pen & Aux Binding) from working, this need to be fixed soon.

**Comment by shmkle** [comment]
tell me if there's any issues with this release https://github.com/shmkle/TemporalResampler/releases/tag/v1.3.0

**Comment by Mrcubix** [comment]
It seems that the issue is fixed, also provide a .zip instead of a .rar in your release.
Close this once it's merged to the plugin repo.
